<a href="https://colab.research.google.com/github/harnalashok/deeplearning/blob/main/pretrained_layers_IV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from tensorflow.keras.datasets import fashion_mnist
import numpy as np

In [32]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [2]:
(X_train, y_train), (X_test,y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [18]:
X_train.shape

(60000, 28, 28)

In [8]:
items = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [9]:
X_train = X_train/255.0
X_test = X_test/255.0

array([False, False, False, ..., False, False,  True])

In [44]:
ss_train = X_train[np.logical_or (y_train == 5,y_train == 6), :, :]
ss_train.shape
ss_test = X_test[np.logical_or (y_test == 5,y_test == 6), :, :]
ss_test.shape
ss_y_train = y_train[np.logical_or (y_train == 5,y_train == 6)]
ss_y_train.shape
ss_y_test = y_test[np.logical_or (y_test == 5,y_test == 6)]
ss_y_test.shape

(12000, 28, 28)

(2000, 28, 28)

(12000,)

(2000,)

In [132]:
ss_y_train[ss_y_train == 6] = 1
ss_y_train[ss_y_train == 5] = 0

In [133]:
ss_y_train

array([0, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [90]:
data_train = X_train[ np.logical_and (y_train != 5 , y_train !=6), :,:]
data_train = data_train.reshape(-1,784)
data_train.shape 
data_test = X_test[ np.logical_and (y_test != 5 , y_test !=6), :,:]
data_test = data_test.reshape(-1,784)
data_test.shape


data_y_train = y_train[ np.logical_and (y_train != 5 , y_train !=6)]
data_y_train.shape 
data_y_test = y_test[ np.logical_and (y_test != 5 , y_test !=6)]
data_y_test.shape



(48000, 784)

(8000, 784)

(48000,)

(8000,)

In [91]:
ss_train = X_train[np.nonzero(np.logical_or (y_train == 5,y_train == 6)), :, :]
ss_train = ss_train.reshape(-1,784)
ss_test = X_train[np.nonzero(np.logical_or (y_train == 5,y_train == 6)), :, :]
ss_test = ss_test.reshape(-1,784)
ss_train.shape
ss_test.shape

(12000, 784)

(12000, 784)

In [96]:
units =100
input = keras.layers.Input(shape = (784,))
x = keras.layers.Dense(units = units, activation = "selu", name = "a")(input)
x = keras.layers.Dense(units = units, activation = "selu", name = "b")(x)
x = keras.layers.Dense(units = units, activation = "selu", name = "c")(x)
out = keras.layers.Dense(units = 10, activation = 'softmax', name = "d")(x)
model = Model(inputs = [input], outputs = [out])
model.compile(loss = "sparse_categorical_crossentropy", metrics = "accuracy")

In [97]:
model.fit(data_train,data_y_train, epochs = 10)

Epoch 1/20
1500/1500 [==============================] - 5s 3ms/step - loss: 0.4761 - accuracy: 0.8322
Epoch 2/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.2578 - accuracy: 0.9067
Epoch 3/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.2260 - accuracy: 0.9186
Epoch 4/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.2123 - accuracy: 0.9239
Epoch 5/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.2013 - accuracy: 0.9274
Epoch 6/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1889 - accuracy: 0.9326
Epoch 7/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1805 - accuracy: 0.9357
Epoch 8/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1708 - accuracy: 0.9389
Epoch 9/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1653 - accuracy: 0.9401
Epoch 10/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.161

In [99]:
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
a (Dense)                    (None, 100)               78500     
_________________________________________________________________
b (Dense)                    (None, 100)               10100     
_________________________________________________________________
c (Dense)                    (None, 100)               10100     
_________________________________________________________________
d (Dense)                    (None, 10)                1010      
Total params: 99,710
Trainable params: 99,710
Non-trainable params: 0
_________________________________________________________________


In [104]:
model.layers
model.layers[3]

In [102]:
for layer in model.layers[:4]:
  layer.trainable = False

In [109]:
tf.saved_model.save(model, "/root/model")


INFO:tensorflow:Assets written to: /root/model/assets


In [110]:
del(model)

In [118]:
model = keras.models.load_model("/root/model")
 


In [119]:
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
a (Dense)                    (None, 100)               78500     
_________________________________________________________________
b (Dense)                    (None, 100)               10100     
_________________________________________________________________
c (Dense)                    (None, 100)               10100     
_________________________________________________________________
d (Dense)                    (None, 10)                1010      
Total params: 99,710
Trainable params: 99,710
Non-trainable params: 0
_________________________________________________________________


In [120]:
units =100
input = keras.layers.Input(shape = (784,))
x = keras.layers.Dense(units = units, activation = "selu", name = "a")(input)
x = keras.layers.Dense(units = units, activation = "selu", name = "b")(x)
x = keras.layers.Dense(units = units, activation = "selu", name = "c")(x)
out = keras.layers.Dense(units = 2, activation = 'softmax', name = "d")(x)

In [122]:
model_1 = Model(inputs = [input], outputs = [out])


In [124]:
model.layers[1].get_weights()

[array([[ 0.0200765 ,  0.03928816,  0.02216594, ...,  0.08818798,
          0.0273401 , -0.01568698],
        [ 0.06713179,  0.03235041, -0.04764441, ..., -0.01043751,
          0.02157476,  0.10488354],
        [-0.33216465,  0.251126  , -0.18246882, ...,  0.3922871 ,
          0.297408  ,  0.25099432],
        ...,
        [ 0.0466023 , -0.1216006 , -0.01429964, ...,  0.26163495,
         -0.16638726,  0.5435451 ],
        [ 0.30099398, -0.329225  ,  0.16592345, ...,  0.07812608,
          0.11534598,  0.227801  ],
        [ 0.00073423, -0.07167973, -0.2865736 , ...,  0.09619594,
          0.24174218,  0.23470792]], dtype=float32),
 array([-2.36573309e-01, -2.35280357e-02,  1.04582310e-02, -2.32576556e-03,
        -8.40267241e-02,  2.33466566e-01, -1.06402397e-01, -1.96787328e-01,
         3.09968114e-01, -4.44545858e-02, -4.51167047e-01,  3.58818546e-02,
        -1.44800574e-01, -4.93491516e-02,  9.34602171e-02,  5.79757988e-02,
         5.08762226e-02, -2.65835792e-01, -3.08039069e

In [125]:
for r in range(4):
  model_1.layers[r].set_weights(model.layers[r].get_weights())

In [127]:
model_1.compile(loss = "sparse_categorical_crossentropy", metrics = "accuracy")

In [134]:
model_1.fit(ss_train,ss_y_train,epochs = 10)


Epoch 1/10
375/375 [==============================] - 1s 2ms/step - loss: 0.0316 - accuracy: 0.9933
Epoch 2/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0032 - accuracy: 0.9995
Epoch 3/10
375/375 [==============================] - 1s 2ms/step - loss: 0.0031 - accuracy: 0.9996
Epoch 4/10
375/375 [==============================] - 1s 2ms/step - loss: 0.0013 - accuracy: 0.9998
Epoch 5/10
375/375 [==============================] - 1s 2ms/step - loss: 8.0996e-04 - accuracy: 0.9998
Epoch 6/10
375/375 [==============================] - 1s 2ms/step - loss: 2.0326e-04 - accuracy: 0.9999
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 1.9579e-05 - accuracy: 1.0000
Epoch 8/10
375/375 [==============================] - 1s 2ms/step - loss: 7.9210e-04 - accuracy: 0.9999
Epoch 9/10
375/375 [==============================] - 1s 2ms/step - loss: 4.5399e-09 - accuracy: 1.0000
Epoch 10/10
375/375 [==============================] - 1s 2ms/step - loss: 1.986